// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.Web.ConfigurationPage;
using Soenneker.Jellyfin.OpenApiClient.Web.ConfigurationPages;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.Web
{
    /// <summary>
    /// Builds and executes requests for operations under \web
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ConfigurationPage property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Web.ConfigurationPage.ConfigurationPageRequestBuilder ConfigurationPage
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Web.ConfigurationPage.ConfigurationPageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ConfigurationPages property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Web.ConfigurationPages.ConfigurationPagesRequestBuilder ConfigurationPages
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Web.ConfigurationPages.ConfigurationPagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Web.WebRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/web", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Web.WebRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/web", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
