// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.EnvironmentNamespace.DefaultDirectoryBrowser;
using Soenneker.Jellyfin.OpenApiClient.EnvironmentNamespace.DirectoryContents;
using Soenneker.Jellyfin.OpenApiClient.EnvironmentNamespace.Drives;
using Soenneker.Jellyfin.OpenApiClient.EnvironmentNamespace.ParentPath;
using Soenneker.Jellyfin.OpenApiClient.EnvironmentNamespace.ValidatePath;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.EnvironmentNamespace
{
    /// <summary>
    /// Builds and executes requests for operations under \Environment
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EnvironmentRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The DefaultDirectoryBrowser property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.EnvironmentNamespace.DefaultDirectoryBrowser.DefaultDirectoryBrowserRequestBuilder DefaultDirectoryBrowser
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.EnvironmentNamespace.DefaultDirectoryBrowser.DefaultDirectoryBrowserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The DirectoryContents property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.EnvironmentNamespace.DirectoryContents.DirectoryContentsRequestBuilder DirectoryContents
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.EnvironmentNamespace.DirectoryContents.DirectoryContentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Drives property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.EnvironmentNamespace.Drives.DrivesRequestBuilder Drives
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.EnvironmentNamespace.Drives.DrivesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ParentPath property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.EnvironmentNamespace.ParentPath.ParentPathRequestBuilder ParentPath
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.EnvironmentNamespace.ParentPath.ParentPathRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ValidatePath property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.EnvironmentNamespace.ValidatePath.ValidatePathRequestBuilder ValidatePath
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.EnvironmentNamespace.ValidatePath.ValidatePathRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.EnvironmentNamespace.EnvironmentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EnvironmentRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Environment", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.EnvironmentNamespace.EnvironmentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EnvironmentRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Environment", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
