// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.QuickConnect.Authorize;
using Soenneker.Jellyfin.OpenApiClient.QuickConnect.Connect;
using Soenneker.Jellyfin.OpenApiClient.QuickConnect.Enabled;
using Soenneker.Jellyfin.OpenApiClient.QuickConnect.Initiate;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.QuickConnect
{
    /// <summary>
    /// Builds and executes requests for operations under \QuickConnect
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QuickConnectRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Authorize property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.QuickConnect.Authorize.AuthorizeRequestBuilder Authorize
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.QuickConnect.Authorize.AuthorizeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Connect property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.QuickConnect.Connect.ConnectRequestBuilder Connect
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.QuickConnect.Connect.ConnectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Enabled property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.QuickConnect.Enabled.EnabledRequestBuilder Enabled
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.QuickConnect.Enabled.EnabledRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Initiate property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.QuickConnect.Initiate.InitiateRequestBuilder Initiate
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.QuickConnect.Initiate.InitiateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.QuickConnect.QuickConnectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QuickConnectRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/QuickConnect", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.QuickConnect.QuickConnectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QuickConnectRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/QuickConnect", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
