// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.Buffering;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.Item;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.Join;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.Leave;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.List;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.MovePlaylistItem;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.New;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.NextItem;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.Pause;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.Ping;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.PreviousItem;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.Queue;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.Ready;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.RemoveFromPlaylist;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.Seek;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.SetIgnoreWait;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.SetNewQueue;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.SetPlaylistItem;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.SetRepeatMode;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.SetShuffleMode;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.Stop;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay.Unpause;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.SyncPlay
{
    /// <summary>
    /// Builds and executes requests for operations under \SyncPlay
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SyncPlayRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Buffering property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Buffering.BufferingRequestBuilder Buffering
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Buffering.BufferingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Join property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Join.JoinRequestBuilder Join
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Join.JoinRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Leave property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Leave.LeaveRequestBuilder Leave
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Leave.LeaveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The List property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.List.ListRequestBuilder List
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The MovePlaylistItem property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.MovePlaylistItem.MovePlaylistItemRequestBuilder MovePlaylistItem
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.MovePlaylistItem.MovePlaylistItemRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The New property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.New.NewRequestBuilder New
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.New.NewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The NextItem property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.NextItem.NextItemRequestBuilder NextItem
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.NextItem.NextItemRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Pause property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Pause.PauseRequestBuilder Pause
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Pause.PauseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Ping property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Ping.PingRequestBuilder Ping
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Ping.PingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The PreviousItem property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.PreviousItem.PreviousItemRequestBuilder PreviousItem
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.PreviousItem.PreviousItemRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Queue property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Queue.QueueRequestBuilder Queue
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Queue.QueueRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Ready property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Ready.ReadyRequestBuilder Ready
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Ready.ReadyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The RemoveFromPlaylist property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.RemoveFromPlaylist.RemoveFromPlaylistRequestBuilder RemoveFromPlaylist
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.RemoveFromPlaylist.RemoveFromPlaylistRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Seek property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Seek.SeekRequestBuilder Seek
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Seek.SeekRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SetIgnoreWait property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.SetIgnoreWait.SetIgnoreWaitRequestBuilder SetIgnoreWait
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.SetIgnoreWait.SetIgnoreWaitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SetNewQueue property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.SetNewQueue.SetNewQueueRequestBuilder SetNewQueue
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.SetNewQueue.SetNewQueueRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SetPlaylistItem property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.SetPlaylistItem.SetPlaylistItemRequestBuilder SetPlaylistItem
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.SetPlaylistItem.SetPlaylistItemRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SetRepeatMode property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.SetRepeatMode.SetRepeatModeRequestBuilder SetRepeatMode
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.SetRepeatMode.SetRepeatModeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SetShuffleMode property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.SetShuffleMode.SetShuffleModeRequestBuilder SetShuffleMode
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.SetShuffleMode.SetShuffleModeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Stop property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Stop.StopRequestBuilder Stop
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Stop.StopRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Unpause property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Unpause.UnpauseRequestBuilder Unpause
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Unpause.UnpauseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Jellyfin.OpenApiClient.SyncPlay.item collection</summary>
        /// <param name="position">The id of the group.</param>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Item.SyncPlayItemRequestBuilder"/></returns>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Item.SyncPlayItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.Item.SyncPlayItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.SyncPlayRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SyncPlayRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/SyncPlay", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.SyncPlayRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SyncPlayRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/SyncPlay", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
