// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.Videos.Item;
using Soenneker.Jellyfin.OpenApiClient.Videos.MergeVersions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.Videos
{
    /// <summary>
    /// Builds and executes requests for operations under \Videos
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VideosRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The MergeVersions property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Videos.MergeVersions.MergeVersionsRequestBuilder MergeVersions
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Videos.MergeVersions.MergeVersionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Jellyfin.OpenApiClient.Videos.item collection</summary>
        /// <param name="position">The item id.</param>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.Videos.Item.ItemItemRequestBuilder"/></returns>
        public global::Soenneker.Jellyfin.OpenApiClient.Videos.Item.ItemItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("item%2Did", position);
                return new global::Soenneker.Jellyfin.OpenApiClient.Videos.Item.ItemItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Videos.VideosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VideosRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Videos", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Videos.VideosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VideosRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Videos", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
