// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.LiveTv.Tuners.Discover;
using Soenneker.Jellyfin.OpenApiClient.LiveTv.Tuners.Discvover;
using Soenneker.Jellyfin.OpenApiClient.LiveTv.Tuners.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.LiveTv.Tuners
{
    /// <summary>
    /// Builds and executes requests for operations under \LiveTv\Tuners
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TunersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Discover property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.LiveTv.Tuners.Discover.DiscoverRequestBuilder Discover
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.LiveTv.Tuners.Discover.DiscoverRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Discvover property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.LiveTv.Tuners.Discvover.DiscvoverRequestBuilder Discvover
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.LiveTv.Tuners.Discvover.DiscvoverRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Jellyfin.OpenApiClient.LiveTv.Tuners.item collection</summary>
        /// <param name="position">Tuner id.</param>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.LiveTv.Tuners.Item.WithTunerItemRequestBuilder"/></returns>
        public global::Soenneker.Jellyfin.OpenApiClient.LiveTv.Tuners.Item.WithTunerItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("tunerId", position);
                return new global::Soenneker.Jellyfin.OpenApiClient.LiveTv.Tuners.Item.WithTunerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.LiveTv.Tuners.TunersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TunersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/LiveTv/Tuners", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.LiveTv.Tuners.TunersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TunersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/LiveTv/Tuners", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
