// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.Providers.Subtitles.Subtitles.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.Providers.Subtitles.Subtitles
{
    /// <summary>
    /// Builds and executes requests for operations under \Providers\Subtitles\Subtitles
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubtitlesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Jellyfin.OpenApiClient.Providers.Subtitles.Subtitles.item collection</summary>
        /// <param name="position">The item id.</param>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.Providers.Subtitles.Subtitles.Item.WithSubtitleItemRequestBuilder"/></returns>
        public global::Soenneker.Jellyfin.OpenApiClient.Providers.Subtitles.Subtitles.Item.WithSubtitleItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("subtitleId", position);
                return new global::Soenneker.Jellyfin.OpenApiClient.Providers.Subtitles.Subtitles.Item.WithSubtitleItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Providers.Subtitles.Subtitles.SubtitlesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SubtitlesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Providers/Subtitles/Subtitles", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Providers.Subtitles.Subtitles.SubtitlesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SubtitlesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Providers/Subtitles/Subtitles", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
