// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.Videos.Item.AdditionalParts;
using Soenneker.Jellyfin.OpenApiClient.Videos.Item.AlternateSources;
using Soenneker.Jellyfin.OpenApiClient.Videos.Item.Item;
using Soenneker.Jellyfin.OpenApiClient.Videos.Item.StreamNamespace;
using Soenneker.Jellyfin.OpenApiClient.Videos.Item.StreamWithContainer;
using Soenneker.Jellyfin.OpenApiClient.Videos.Item.Subtitles;
using Soenneker.Jellyfin.OpenApiClient.Videos.Item.Trickplay;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.Videos.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \Videos\{item-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ItemItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The AdditionalParts property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Videos.Item.AdditionalParts.AdditionalPartsRequestBuilder AdditionalParts
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Videos.Item.AdditionalParts.AdditionalPartsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The AlternateSources property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Videos.Item.AlternateSources.AlternateSourcesRequestBuilder AlternateSources
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Videos.Item.AlternateSources.AlternateSourcesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stream property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Videos.Item.StreamNamespace.StreamRequestBuilder Stream
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Videos.Item.StreamNamespace.StreamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Subtitles property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Videos.Item.Subtitles.SubtitlesRequestBuilder Subtitles
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Videos.Item.Subtitles.SubtitlesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Trickplay property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Videos.Item.Trickplay.TrickplayRequestBuilder Trickplay
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Videos.Item.Trickplay.TrickplayRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Jellyfin.OpenApiClient.Videos.item.item collection</summary>
        /// <param name="position">The media source id.</param>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.Videos.Item.Item.MediaSourceItemRequestBuilder"/></returns>
        public global::Soenneker.Jellyfin.OpenApiClient.Videos.Item.Item.MediaSourceItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("mediaSource%2Did", position);
                return new global::Soenneker.Jellyfin.OpenApiClient.Videos.Item.Item.MediaSourceItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Videos.Item.ItemItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ItemItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Videos/{item%2Did}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Videos.Item.ItemItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ItemItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Videos/{item%2Did}", rawUrl)
        {
        }
        /// <summary>
        /// Builds and executes requests for operations under \Videos\{item-id}\stream.{container}
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.Videos.Item.StreamWithContainer.StreamWithContainerRequestBuilder"/></returns>
        /// <param name="container">The video container. Possible values are: ts, webm, asf, wmv, ogv, mp4, m4v, mkv, mpeg, mpg, avi, 3gp, wmv, wtv, m2ts, mov, iso, flv.</param>
        public global::Soenneker.Jellyfin.OpenApiClient.Videos.Item.StreamWithContainer.StreamWithContainerRequestBuilder StreamWithContainer(string container)
        {
            if(string.IsNullOrEmpty(container)) throw new ArgumentNullException(nameof(container));
            return new global::Soenneker.Jellyfin.OpenApiClient.Videos.Item.StreamWithContainer.StreamWithContainerRequestBuilder(PathParameters, RequestAdapter, container);
        }
    }
}
#pragma warning restore CS0618
