// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.Localization.Countries;
using Soenneker.Jellyfin.OpenApiClient.Localization.Cultures;
using Soenneker.Jellyfin.OpenApiClient.Localization.Options;
using Soenneker.Jellyfin.OpenApiClient.Localization.ParentalRatings;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.Localization
{
    /// <summary>
    /// Builds and executes requests for operations under \Localization
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LocalizationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Countries property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Localization.Countries.CountriesRequestBuilder Countries
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Localization.Countries.CountriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Cultures property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Localization.Cultures.CulturesRequestBuilder Cultures
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Localization.Cultures.CulturesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The OptionsPath property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Localization.Options.OptionsRequestBuilder OptionsPath
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Localization.Options.OptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ParentalRatings property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Localization.ParentalRatings.ParentalRatingsRequestBuilder ParentalRatings
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Localization.ParentalRatings.ParentalRatingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Localization.LocalizationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LocalizationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Localization", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Localization.LocalizationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LocalizationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Localization", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
