// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.Apply;
using Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.Book;
using Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.BoxSet;
using Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.Movie;
using Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.MusicAlbum;
using Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.MusicArtist;
using Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.MusicVideo;
using Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.Person;
using Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.Series;
using Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.Trailer;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch
{
    /// <summary>
    /// Builds and executes requests for operations under \Items\RemoteSearch
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RemoteSearchRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Apply property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.Apply.ApplyRequestBuilder Apply
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.Apply.ApplyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Book property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.Book.BookRequestBuilder Book
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.Book.BookRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The BoxSet property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.BoxSet.BoxSetRequestBuilder BoxSet
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.BoxSet.BoxSetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Movie property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.Movie.MovieRequestBuilder Movie
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.Movie.MovieRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The MusicAlbum property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.MusicAlbum.MusicAlbumRequestBuilder MusicAlbum
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.MusicAlbum.MusicAlbumRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The MusicArtist property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.MusicArtist.MusicArtistRequestBuilder MusicArtist
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.MusicArtist.MusicArtistRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The MusicVideo property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.MusicVideo.MusicVideoRequestBuilder MusicVideo
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.MusicVideo.MusicVideoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Person property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.Person.PersonRequestBuilder Person
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.Person.PersonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Series property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.Series.SeriesRequestBuilder Series
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.Series.SeriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Trailer property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.Trailer.TrailerRequestBuilder Trailer
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.Trailer.TrailerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.RemoteSearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RemoteSearchRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Items/RemoteSearch", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Items.RemoteSearch.RemoteSearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RemoteSearchRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Items/RemoteSearch", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
