// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.UserPlayedItems.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.UserPlayedItems
{
    /// <summary>
    /// Builds and executes requests for operations under \UserPlayedItems
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserPlayedItemsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Jellyfin.OpenApiClient.UserPlayedItems.item collection</summary>
        /// <param name="position">Item id.</param>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.UserPlayedItems.Item.WithItemItemRequestBuilder"/></returns>
        public global::Soenneker.Jellyfin.OpenApiClient.UserPlayedItems.Item.WithItemItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("itemId", position);
                return new global::Soenneker.Jellyfin.OpenApiClient.UserPlayedItems.Item.WithItemItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.UserPlayedItems.UserPlayedItemsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserPlayedItemsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/UserPlayedItems", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.UserPlayedItems.UserPlayedItemsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserPlayedItemsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/UserPlayedItems", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
