// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.LiveTv.ListingProviders.SchedulesDirect.Countries;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.LiveTv.ListingProviders.SchedulesDirect
{
    /// <summary>
    /// Builds and executes requests for operations under \LiveTv\ListingProviders\SchedulesDirect
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SchedulesDirectRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Countries property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.LiveTv.ListingProviders.SchedulesDirect.Countries.CountriesRequestBuilder Countries
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.LiveTv.ListingProviders.SchedulesDirect.Countries.CountriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.LiveTv.ListingProviders.SchedulesDirect.SchedulesDirectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SchedulesDirectRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/LiveTv/ListingProviders/SchedulesDirect", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.LiveTv.ListingProviders.SchedulesDirect.SchedulesDirectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SchedulesDirectRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/LiveTv/ListingProviders/SchedulesDirect", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
