// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.Playback.BitrateTest;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.Playback
{
    /// <summary>
    /// Builds and executes requests for operations under \Playback
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PlaybackRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The BitrateTest property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Playback.BitrateTest.BitrateTestRequestBuilder BitrateTest
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Playback.BitrateTest.BitrateTestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Playback.PlaybackRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlaybackRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Playback", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Playback.PlaybackRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlaybackRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Playback", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
