// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.Models;
using Soenneker.Jellyfin.OpenApiClient.Users.AuthenticateByName;
using Soenneker.Jellyfin.OpenApiClient.Users.AuthenticateWithQuickConnect;
using Soenneker.Jellyfin.OpenApiClient.Users.Configuration;
using Soenneker.Jellyfin.OpenApiClient.Users.ForgotPassword;
using Soenneker.Jellyfin.OpenApiClient.Users.Item;
using Soenneker.Jellyfin.OpenApiClient.Users.Me;
using Soenneker.Jellyfin.OpenApiClient.Users.New;
using Soenneker.Jellyfin.OpenApiClient.Users.Password;
using Soenneker.Jellyfin.OpenApiClient.Users.Public;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.Users
{
    /// <summary>
    /// Builds and executes requests for operations under \Users
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The AuthenticateByName property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Users.AuthenticateByName.AuthenticateByNameRequestBuilder AuthenticateByName
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Users.AuthenticateByName.AuthenticateByNameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The AuthenticateWithQuickConnect property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Users.AuthenticateWithQuickConnect.AuthenticateWithQuickConnectRequestBuilder AuthenticateWithQuickConnect
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Users.AuthenticateWithQuickConnect.AuthenticateWithQuickConnectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Configuration property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Users.Configuration.ConfigurationRequestBuilder Configuration
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Users.Configuration.ConfigurationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ForgotPassword property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Users.ForgotPassword.ForgotPasswordRequestBuilder ForgotPassword
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Users.ForgotPassword.ForgotPasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Me property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Users.Me.MeRequestBuilder Me
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Users.Me.MeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The New property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Users.New.NewRequestBuilder New
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Users.New.NewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Password property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Users.Password.PasswordRequestBuilder Password
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Users.Password.PasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Public property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Users.Public.PublicRequestBuilder Public
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Users.Public.PublicRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Jellyfin.OpenApiClient.Users.item collection</summary>
        /// <param name="position">The user id.</param>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.Users.Item.WithUserItemRequestBuilder"/></returns>
        public global::Soenneker.Jellyfin.OpenApiClient.Users.Item.WithUserItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("userId", position);
                return new global::Soenneker.Jellyfin.OpenApiClient.Users.Item.WithUserItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Users{?isDisabled*,isHidden*,userId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Users{?isDisabled*,isHidden*,userId*}", rawUrl)
        {
        }
        /// <summary>
        /// Gets a list of users.
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Jellyfin.OpenApiClient.Models.UserDto&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Jellyfin.OpenApiClient.Models.UserDto>?> GetAsync(Action<RequestConfiguration<global::Soenneker.Jellyfin.OpenApiClient.Users.UsersRequestBuilder.UsersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Jellyfin.OpenApiClient.Models.UserDto>> GetAsync(Action<RequestConfiguration<global::Soenneker.Jellyfin.OpenApiClient.Users.UsersRequestBuilder.UsersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Jellyfin.OpenApiClient.Models.UserDto>(requestInfo, global::Soenneker.Jellyfin.OpenApiClient.Models.UserDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Updates a user.
        /// </summary>
        /// <param name="body">Class UserDto.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Jellyfin.OpenApiClient.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Jellyfin.OpenApiClient.Models.ProblemDetails">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PostAsync(global::Soenneker.Jellyfin.OpenApiClient.Models.UserDto body, Action<RequestConfiguration<global::Soenneker.Jellyfin.OpenApiClient.Users.UsersRequestBuilder.UsersRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PostAsync(global::Soenneker.Jellyfin.OpenApiClient.Models.UserDto body, Action<RequestConfiguration<global::Soenneker.Jellyfin.OpenApiClient.Users.UsersRequestBuilder.UsersRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Jellyfin.OpenApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Jellyfin.OpenApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets a list of users.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Jellyfin.OpenApiClient.Users.UsersRequestBuilder.UsersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Jellyfin.OpenApiClient.Users.UsersRequestBuilder.UsersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates a user.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Class UserDto.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Jellyfin.OpenApiClient.Models.UserDto body, Action<RequestConfiguration<global::Soenneker.Jellyfin.OpenApiClient.Users.UsersRequestBuilder.UsersRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Jellyfin.OpenApiClient.Models.UserDto body, Action<RequestConfiguration<global::Soenneker.Jellyfin.OpenApiClient.Users.UsersRequestBuilder.UsersRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, application/json;profile=\"CamelCase\", application/json;profile=\"PascalCase\"");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.Users.UsersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Jellyfin.OpenApiClient.Users.UsersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Jellyfin.OpenApiClient.Users.UsersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Gets a list of users.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UsersRequestBuilderGetQueryParameters 
        {
            /// <summary>Optional filter by IsDisabled=true or false.</summary>
            [QueryParameter("isDisabled")]
            public bool? IsDisabled { get; set; }
            /// <summary>Optional filter by IsHidden=true or false.</summary>
            [QueryParameter("isHidden")]
            public bool? IsHidden { get; set; }
        }
        /// <summary>
        /// Updates a user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UsersRequestBuilderPostQueryParameters 
        {
            /// <summary>The user id.</summary>
            [QueryParameter("userId")]
            public Guid? UserId { get; set; }
        }
    }
}
#pragma warning restore CS0618
