// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.Audio.Item.Lyrics;
using Soenneker.Jellyfin.OpenApiClient.Audio.Item.RemoteSearch;
using Soenneker.Jellyfin.OpenApiClient.Audio.Item.StreamNamespace;
using Soenneker.Jellyfin.OpenApiClient.Audio.Item.StreamWithContainer;
using Soenneker.Jellyfin.OpenApiClient.Audio.Item.Universal;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.Audio.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \Audio\{itemId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithItemItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Lyrics property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Audio.Item.Lyrics.LyricsRequestBuilder Lyrics
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Audio.Item.Lyrics.LyricsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The RemoteSearch property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Audio.Item.RemoteSearch.RemoteSearchRequestBuilder RemoteSearch
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Audio.Item.RemoteSearch.RemoteSearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stream property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Audio.Item.StreamNamespace.StreamRequestBuilder Stream
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Audio.Item.StreamNamespace.StreamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The universal property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Audio.Item.Universal.UniversalRequestBuilder Universal
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Audio.Item.Universal.UniversalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Audio.Item.WithItemItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithItemItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Audio/{itemId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Audio.Item.WithItemItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithItemItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Audio/{itemId}", rawUrl)
        {
        }
        /// <summary>
        /// Builds and executes requests for operations under \Audio\{itemId}\stream.{container}
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.Audio.Item.StreamWithContainer.StreamWithContainerRequestBuilder"/></returns>
        /// <param name="container">The audio container.</param>
        public global::Soenneker.Jellyfin.OpenApiClient.Audio.Item.StreamWithContainer.StreamWithContainerRequestBuilder StreamWithContainer(string container)
        {
            if(string.IsNullOrEmpty(container)) throw new ArgumentNullException(nameof(container));
            return new global::Soenneker.Jellyfin.OpenApiClient.Audio.Item.StreamWithContainer.StreamWithContainerRequestBuilder(PathParameters, RequestAdapter, container);
        }
    }
}
#pragma warning restore CS0618
