// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.LiveTv.ChannelMappingOptions;
using Soenneker.Jellyfin.OpenApiClient.LiveTv.ChannelMappings;
using Soenneker.Jellyfin.OpenApiClient.LiveTv.Channels;
using Soenneker.Jellyfin.OpenApiClient.LiveTv.GuideInfo;
using Soenneker.Jellyfin.OpenApiClient.LiveTv.Info;
using Soenneker.Jellyfin.OpenApiClient.LiveTv.ListingProviders;
using Soenneker.Jellyfin.OpenApiClient.LiveTv.LiveRecordings;
using Soenneker.Jellyfin.OpenApiClient.LiveTv.LiveStreamFiles;
using Soenneker.Jellyfin.OpenApiClient.LiveTv.Programs;
using Soenneker.Jellyfin.OpenApiClient.LiveTv.Recordings;
using Soenneker.Jellyfin.OpenApiClient.LiveTv.SeriesTimers;
using Soenneker.Jellyfin.OpenApiClient.LiveTv.Timers;
using Soenneker.Jellyfin.OpenApiClient.LiveTv.TunerHosts;
using Soenneker.Jellyfin.OpenApiClient.LiveTv.Tuners;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.LiveTv
{
    /// <summary>
    /// Builds and executes requests for operations under \LiveTv
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LiveTvRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ChannelMappingOptions property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.LiveTv.ChannelMappingOptions.ChannelMappingOptionsRequestBuilder ChannelMappingOptions
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.LiveTv.ChannelMappingOptions.ChannelMappingOptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ChannelMappings property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.LiveTv.ChannelMappings.ChannelMappingsRequestBuilder ChannelMappings
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.LiveTv.ChannelMappings.ChannelMappingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Channels property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.LiveTv.Channels.ChannelsRequestBuilder Channels
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.LiveTv.Channels.ChannelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GuideInfo property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.LiveTv.GuideInfo.GuideInfoRequestBuilder GuideInfo
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.LiveTv.GuideInfo.GuideInfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Info property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.LiveTv.Info.InfoRequestBuilder Info
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.LiveTv.Info.InfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ListingProviders property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.LiveTv.ListingProviders.ListingProvidersRequestBuilder ListingProviders
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.LiveTv.ListingProviders.ListingProvidersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The LiveRecordings property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.LiveTv.LiveRecordings.LiveRecordingsRequestBuilder LiveRecordings
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.LiveTv.LiveRecordings.LiveRecordingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The LiveStreamFiles property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.LiveTv.LiveStreamFiles.LiveStreamFilesRequestBuilder LiveStreamFiles
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.LiveTv.LiveStreamFiles.LiveStreamFilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Programs property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.LiveTv.Programs.ProgramsRequestBuilder Programs
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.LiveTv.Programs.ProgramsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Recordings property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.LiveTv.Recordings.RecordingsRequestBuilder Recordings
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.LiveTv.Recordings.RecordingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SeriesTimers property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.LiveTv.SeriesTimers.SeriesTimersRequestBuilder SeriesTimers
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.LiveTv.SeriesTimers.SeriesTimersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Timers property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.LiveTv.Timers.TimersRequestBuilder Timers
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.LiveTv.Timers.TimersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The TunerHosts property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.LiveTv.TunerHosts.TunerHostsRequestBuilder TunerHosts
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.LiveTv.TunerHosts.TunerHostsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Tuners property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.LiveTv.Tuners.TunersRequestBuilder Tuners
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.LiveTv.Tuners.TunersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.LiveTv.LiveTvRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LiveTvRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/LiveTv", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.LiveTv.LiveTvRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LiveTvRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/LiveTv", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
