// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.FallbackFont.Fonts;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.FallbackFont
{
    /// <summary>
    /// Builds and executes requests for operations under \FallbackFont
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FallbackFontRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Fonts property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.FallbackFont.Fonts.FontsRequestBuilder Fonts
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.FallbackFont.Fonts.FontsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.FallbackFont.FallbackFontRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FallbackFontRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/FallbackFont", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.FallbackFont.FallbackFontRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FallbackFontRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/FallbackFont", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
