// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Soenneker.Jellyfin.OpenApiClient.Albums;
using Soenneker.Jellyfin.OpenApiClient.Artists;
using Soenneker.Jellyfin.OpenApiClient.Audio;
using Soenneker.Jellyfin.OpenApiClient.Auth;
using Soenneker.Jellyfin.OpenApiClient.Backup;
using Soenneker.Jellyfin.OpenApiClient.Branding;
using Soenneker.Jellyfin.OpenApiClient.Channels;
using Soenneker.Jellyfin.OpenApiClient.ClientLog;
using Soenneker.Jellyfin.OpenApiClient.Collections;
using Soenneker.Jellyfin.OpenApiClient.Devices;
using Soenneker.Jellyfin.OpenApiClient.DisplayPreferences;
using Soenneker.Jellyfin.OpenApiClient.EnvironmentNamespace;
using Soenneker.Jellyfin.OpenApiClient.FallbackFont;
using Soenneker.Jellyfin.OpenApiClient.Genres;
using Soenneker.Jellyfin.OpenApiClient.GetUtcTime;
using Soenneker.Jellyfin.OpenApiClient.Items;
using Soenneker.Jellyfin.OpenApiClient.Libraries;
using Soenneker.Jellyfin.OpenApiClient.Library;
using Soenneker.Jellyfin.OpenApiClient.LiveStreams;
using Soenneker.Jellyfin.OpenApiClient.LiveTv;
using Soenneker.Jellyfin.OpenApiClient.Localization;
using Soenneker.Jellyfin.OpenApiClient.MediaSegments;
using Soenneker.Jellyfin.OpenApiClient.Movies;
using Soenneker.Jellyfin.OpenApiClient.MusicGenres;
using Soenneker.Jellyfin.OpenApiClient.Packages;
using Soenneker.Jellyfin.OpenApiClient.Persons;
using Soenneker.Jellyfin.OpenApiClient.Playback;
using Soenneker.Jellyfin.OpenApiClient.Playlists;
using Soenneker.Jellyfin.OpenApiClient.Plugins;
using Soenneker.Jellyfin.OpenApiClient.Providers;
using Soenneker.Jellyfin.OpenApiClient.QuickConnect;
using Soenneker.Jellyfin.OpenApiClient.Repositories;
using Soenneker.Jellyfin.OpenApiClient.ScheduledTasks;
using Soenneker.Jellyfin.OpenApiClient.Search;
using Soenneker.Jellyfin.OpenApiClient.Sessions;
using Soenneker.Jellyfin.OpenApiClient.Shows;
using Soenneker.Jellyfin.OpenApiClient.Songs;
using Soenneker.Jellyfin.OpenApiClient.Startup;
using Soenneker.Jellyfin.OpenApiClient.Studios;
using Soenneker.Jellyfin.OpenApiClient.SyncPlay;
using Soenneker.Jellyfin.OpenApiClient.System;
using Soenneker.Jellyfin.OpenApiClient.Trailers;
using Soenneker.Jellyfin.OpenApiClient.UserFavoriteItems;
using Soenneker.Jellyfin.OpenApiClient.UserImage;
using Soenneker.Jellyfin.OpenApiClient.UserItems;
using Soenneker.Jellyfin.OpenApiClient.UserPlayedItems;
using Soenneker.Jellyfin.OpenApiClient.UserViews;
using Soenneker.Jellyfin.OpenApiClient.Users;
using Soenneker.Jellyfin.OpenApiClient.Videos;
using Soenneker.Jellyfin.OpenApiClient.Web;
using Soenneker.Jellyfin.OpenApiClient.Years;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class JellyfinOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The Albums property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Albums.AlbumsRequestBuilder Albums
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Albums.AlbumsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Artists property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Artists.ArtistsRequestBuilder Artists
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Artists.ArtistsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Audio property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Audio.AudioRequestBuilder Audio
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Audio.AudioRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Auth property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Auth.AuthRequestBuilder Auth
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Backup property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Backup.BackupRequestBuilder Backup
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Backup.BackupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Branding property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Branding.BrandingRequestBuilder Branding
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Branding.BrandingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Channels property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Channels.ChannelsRequestBuilder Channels
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Channels.ChannelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ClientLog property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.ClientLog.ClientLogRequestBuilder ClientLog
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.ClientLog.ClientLogRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Collections property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Collections.CollectionsRequestBuilder Collections
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Collections.CollectionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Devices property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Devices.DevicesRequestBuilder Devices
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Devices.DevicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The DisplayPreferences property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.DisplayPreferences.DisplayPreferencesRequestBuilder DisplayPreferences
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.DisplayPreferences.DisplayPreferencesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Environment property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.EnvironmentNamespace.EnvironmentRequestBuilder Environment
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.EnvironmentNamespace.EnvironmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The FallbackFont property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.FallbackFont.FallbackFontRequestBuilder FallbackFont
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.FallbackFont.FallbackFontRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Genres property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Genres.GenresRequestBuilder Genres
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Genres.GenresRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetUtcTime property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.GetUtcTime.GetUtcTimeRequestBuilder GetUtcTime
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.GetUtcTime.GetUtcTimeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Items property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.ItemsRequestBuilder Items
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.ItemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Libraries property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Libraries.LibrariesRequestBuilder Libraries
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Libraries.LibrariesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Library property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Library.LibraryRequestBuilder Library
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Library.LibraryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The LiveStreams property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.LiveStreams.LiveStreamsRequestBuilder LiveStreams
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.LiveStreams.LiveStreamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The LiveTv property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.LiveTv.LiveTvRequestBuilder LiveTv
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.LiveTv.LiveTvRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Localization property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Localization.LocalizationRequestBuilder Localization
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Localization.LocalizationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The MediaSegments property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.MediaSegments.MediaSegmentsRequestBuilder MediaSegments
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.MediaSegments.MediaSegmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Movies property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Movies.MoviesRequestBuilder Movies
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Movies.MoviesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The MusicGenres property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.MusicGenres.MusicGenresRequestBuilder MusicGenres
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.MusicGenres.MusicGenresRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Packages property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Packages.PackagesRequestBuilder Packages
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Packages.PackagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Persons property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Persons.PersonsRequestBuilder Persons
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Persons.PersonsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Playback property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Playback.PlaybackRequestBuilder Playback
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Playback.PlaybackRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Playlists property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Playlists.PlaylistsRequestBuilder Playlists
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Playlists.PlaylistsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Plugins property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Plugins.PluginsRequestBuilder Plugins
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Plugins.PluginsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Providers property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Providers.ProvidersRequestBuilder Providers
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Providers.ProvidersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The QuickConnect property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.QuickConnect.QuickConnectRequestBuilder QuickConnect
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.QuickConnect.QuickConnectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Repositories property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Repositories.RepositoriesRequestBuilder Repositories
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Repositories.RepositoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ScheduledTasks property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.ScheduledTasks.ScheduledTasksRequestBuilder ScheduledTasks
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.ScheduledTasks.ScheduledTasksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Search property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Search.SearchRequestBuilder Search
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Sessions property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Sessions.SessionsRequestBuilder Sessions
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Sessions.SessionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Shows property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Shows.ShowsRequestBuilder Shows
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Shows.ShowsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Songs property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Songs.SongsRequestBuilder Songs
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Songs.SongsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Startup property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Startup.StartupRequestBuilder Startup
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Startup.StartupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Studios property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Studios.StudiosRequestBuilder Studios
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Studios.StudiosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SyncPlay property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.SyncPlayRequestBuilder SyncPlay
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.SyncPlay.SyncPlayRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The System property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.System.SystemRequestBuilder System
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.System.SystemRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Trailers property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Trailers.TrailersRequestBuilder Trailers
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Trailers.TrailersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UserFavoriteItems property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.UserFavoriteItems.UserFavoriteItemsRequestBuilder UserFavoriteItems
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.UserFavoriteItems.UserFavoriteItemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UserImage property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.UserImage.UserImageRequestBuilder UserImage
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.UserImage.UserImageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UserItems property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.UserItems.UserItemsRequestBuilder UserItems
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.UserItems.UserItemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UserPlayedItems property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.UserPlayedItems.UserPlayedItemsRequestBuilder UserPlayedItems
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.UserPlayedItems.UserPlayedItemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Users property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UserViews property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.UserViews.UserViewsRequestBuilder UserViews
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.UserViews.UserViewsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Videos property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Videos.VideosRequestBuilder Videos
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Videos.VideosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The web property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Web.WebRequestBuilder Web
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Web.WebRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Years property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Years.YearsRequestBuilder Years
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Years.YearsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.JellyfinOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public JellyfinOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "http://localhost";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
