// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.Items.Item.Ancestors;
using Soenneker.Jellyfin.OpenApiClient.Items.Item.Collections;
using Soenneker.Jellyfin.OpenApiClient.Items.Item.ContentType;
using Soenneker.Jellyfin.OpenApiClient.Items.Item.Download;
using Soenneker.Jellyfin.OpenApiClient.Items.Item.ExternalIdInfos;
using Soenneker.Jellyfin.OpenApiClient.Items.Item.FileNamespace;
using Soenneker.Jellyfin.OpenApiClient.Items.Item.Images;
using Soenneker.Jellyfin.OpenApiClient.Items.Item.InstantMix;
using Soenneker.Jellyfin.OpenApiClient.Items.Item.Intros;
using Soenneker.Jellyfin.OpenApiClient.Items.Item.LocalTrailers;
using Soenneker.Jellyfin.OpenApiClient.Items.Item.MetadataEditor;
using Soenneker.Jellyfin.OpenApiClient.Items.Item.PlaybackInfo;
using Soenneker.Jellyfin.OpenApiClient.Items.Item.Refresh;
using Soenneker.Jellyfin.OpenApiClient.Items.Item.RemoteImages;
using Soenneker.Jellyfin.OpenApiClient.Items.Item.RemoteSearch;
using Soenneker.Jellyfin.OpenApiClient.Items.Item.Similar;
using Soenneker.Jellyfin.OpenApiClient.Items.Item.SpecialFeatures;
using Soenneker.Jellyfin.OpenApiClient.Items.Item.ThemeMedia;
using Soenneker.Jellyfin.OpenApiClient.Items.Item.ThemeSongs;
using Soenneker.Jellyfin.OpenApiClient.Items.Item.ThemeVideos;
using Soenneker.Jellyfin.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.Items.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \Items\{itemId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithItemItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Ancestors property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.Item.Ancestors.AncestorsRequestBuilder Ancestors
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.Item.Ancestors.AncestorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Collections property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.Item.Collections.CollectionsRequestBuilder Collections
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.Item.Collections.CollectionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ContentType property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.Item.ContentType.ContentTypeRequestBuilder ContentType
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.Item.ContentType.ContentTypeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Download property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.Item.Download.DownloadRequestBuilder Download
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.Item.Download.DownloadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ExternalIdInfos property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.Item.ExternalIdInfos.ExternalIdInfosRequestBuilder ExternalIdInfos
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.Item.ExternalIdInfos.ExternalIdInfosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The File property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.Item.FileNamespace.FileRequestBuilder File
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.Item.FileNamespace.FileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Images property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.Item.Images.ImagesRequestBuilder Images
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.Item.Images.ImagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The InstantMix property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.Item.InstantMix.InstantMixRequestBuilder InstantMix
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.Item.InstantMix.InstantMixRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Intros property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.Item.Intros.IntrosRequestBuilder Intros
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.Item.Intros.IntrosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The LocalTrailers property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.Item.LocalTrailers.LocalTrailersRequestBuilder LocalTrailers
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.Item.LocalTrailers.LocalTrailersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The MetadataEditor property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.Item.MetadataEditor.MetadataEditorRequestBuilder MetadataEditor
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.Item.MetadataEditor.MetadataEditorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The PlaybackInfo property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.Item.PlaybackInfo.PlaybackInfoRequestBuilder PlaybackInfo
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.Item.PlaybackInfo.PlaybackInfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Refresh property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.Item.Refresh.RefreshRequestBuilder Refresh
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.Item.Refresh.RefreshRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The RemoteImages property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.Item.RemoteImages.RemoteImagesRequestBuilder RemoteImages
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.Item.RemoteImages.RemoteImagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The RemoteSearch property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.Item.RemoteSearch.RemoteSearchRequestBuilder RemoteSearch
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.Item.RemoteSearch.RemoteSearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Similar property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.Item.Similar.SimilarRequestBuilder Similar
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.Item.Similar.SimilarRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SpecialFeatures property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.Item.SpecialFeatures.SpecialFeaturesRequestBuilder SpecialFeatures
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.Item.SpecialFeatures.SpecialFeaturesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ThemeMedia property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.Item.ThemeMedia.ThemeMediaRequestBuilder ThemeMedia
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.Item.ThemeMedia.ThemeMediaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ThemeSongs property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.Item.ThemeSongs.ThemeSongsRequestBuilder ThemeSongs
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.Item.ThemeSongs.ThemeSongsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ThemeVideos property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.Item.ThemeVideos.ThemeVideosRequestBuilder ThemeVideos
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Items.Item.ThemeVideos.ThemeVideosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Items.Item.WithItemItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithItemItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Items/{itemId}{?userId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Items.Item.WithItemItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithItemItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Items/{itemId}{?userId*}", rawUrl)
        {
        }
        /// <summary>
        /// Deletes an item from the library and filesystem.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Jellyfin.OpenApiClient.Models.ProblemDetails">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Jellyfin.OpenApiClient.Models.ProblemDetails">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Jellyfin.OpenApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Jellyfin.OpenApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets an item from a user&apos;s library.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.Models.BaseItemDto"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Jellyfin.OpenApiClient.Models.BaseItemDto?> GetAsync(Action<RequestConfiguration<global::Soenneker.Jellyfin.OpenApiClient.Items.Item.WithItemItemRequestBuilder.WithItemItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Jellyfin.OpenApiClient.Models.BaseItemDto> GetAsync(Action<RequestConfiguration<global::Soenneker.Jellyfin.OpenApiClient.Items.Item.WithItemItemRequestBuilder.WithItemItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Jellyfin.OpenApiClient.Models.BaseItemDto>(requestInfo, global::Soenneker.Jellyfin.OpenApiClient.Models.BaseItemDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates an item.
        /// </summary>
        /// <param name="body">This is strictly used as a data transfer object from the api layer.This holds information about a BaseItem in a format that is convenient for the client.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Jellyfin.OpenApiClient.Models.ProblemDetails">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PostAsync(global::Soenneker.Jellyfin.OpenApiClient.Models.BaseItemDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PostAsync(global::Soenneker.Jellyfin.OpenApiClient.Models.BaseItemDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Soenneker.Jellyfin.OpenApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes an item from the library and filesystem.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, application/json;profile=\"CamelCase\", application/json;profile=\"PascalCase\"");
            return requestInfo;
        }
        /// <summary>
        /// Gets an item from a user&apos;s library.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Jellyfin.OpenApiClient.Items.Item.WithItemItemRequestBuilder.WithItemItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Jellyfin.OpenApiClient.Items.Item.WithItemItemRequestBuilder.WithItemItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, application/json;profile=\"CamelCase\", application/json;profile=\"PascalCase\"");
            return requestInfo;
        }
        /// <summary>
        /// Updates an item.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">This is strictly used as a data transfer object from the api layer.This holds information about a BaseItem in a format that is convenient for the client.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Jellyfin.OpenApiClient.Models.BaseItemDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Jellyfin.OpenApiClient.Models.BaseItemDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, application/json;profile=\"CamelCase\", application/json;profile=\"PascalCase\"");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.Items.Item.WithItemItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Jellyfin.OpenApiClient.Items.Item.WithItemItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Jellyfin.OpenApiClient.Items.Item.WithItemItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Gets an item from a user&apos;s library.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithItemItemRequestBuilderGetQueryParameters 
        {
            /// <summary>User id.</summary>
            [QueryParameter("userId")]
            public Guid? UserId { get; set; }
        }
    }
}
#pragma warning restore CS0618
