// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.Models;
using Soenneker.Jellyfin.OpenApiClient.Packages.Installed;
using Soenneker.Jellyfin.OpenApiClient.Packages.Installing;
using Soenneker.Jellyfin.OpenApiClient.Packages.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.Packages
{
    /// <summary>
    /// Builds and executes requests for operations under \Packages
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PackagesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Installed property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Packages.Installed.InstalledRequestBuilder Installed
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Packages.Installed.InstalledRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Installing property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Packages.Installing.InstallingRequestBuilder Installing
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Packages.Installing.InstallingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Jellyfin.OpenApiClient.Packages.item collection</summary>
        /// <param name="position">The name of the package.</param>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.Packages.Item.WithNameItemRequestBuilder"/></returns>
        public global::Soenneker.Jellyfin.OpenApiClient.Packages.Item.WithNameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("name", position);
                return new global::Soenneker.Jellyfin.OpenApiClient.Packages.Item.WithNameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Packages.PackagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PackagesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Packages", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Packages.PackagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PackagesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Packages", rawUrl)
        {
        }
        /// <summary>
        /// Gets available packages.
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Jellyfin.OpenApiClient.Models.PackageInfo&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Jellyfin.OpenApiClient.Models.PackageInfo>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Jellyfin.OpenApiClient.Models.PackageInfo>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Jellyfin.OpenApiClient.Models.PackageInfo>(requestInfo, global::Soenneker.Jellyfin.OpenApiClient.Models.PackageInfo.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Gets available packages.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.Packages.PackagesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Jellyfin.OpenApiClient.Packages.PackagesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Jellyfin.OpenApiClient.Packages.PackagesRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
