// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.Sessions.Item.Command;
using Soenneker.Jellyfin.OpenApiClient.Sessions.Item.Message;
using Soenneker.Jellyfin.OpenApiClient.Sessions.Item.Playing;
using Soenneker.Jellyfin.OpenApiClient.Sessions.Item.System;
using Soenneker.Jellyfin.OpenApiClient.Sessions.Item.User;
using Soenneker.Jellyfin.OpenApiClient.Sessions.Item.Viewing;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.Sessions.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \Sessions\{sessionId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSessionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Command property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Sessions.Item.Command.CommandRequestBuilder Command
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Sessions.Item.Command.CommandRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Message property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Sessions.Item.Message.MessageRequestBuilder Message
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Sessions.Item.Message.MessageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Playing property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Sessions.Item.Playing.PlayingRequestBuilder Playing
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Sessions.Item.Playing.PlayingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The System property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Sessions.Item.System.SystemRequestBuilder System
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Sessions.Item.System.SystemRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The User property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Sessions.Item.User.UserRequestBuilder User
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Sessions.Item.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Viewing property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Sessions.Item.Viewing.ViewingRequestBuilder Viewing
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.Sessions.Item.Viewing.ViewingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Sessions.Item.WithSessionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSessionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Sessions/{sessionId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.Sessions.Item.WithSessionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSessionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Sessions/{sessionId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
