// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.UserItems.Item;
using Soenneker.Jellyfin.OpenApiClient.UserItems.Resume;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.UserItems
{
    /// <summary>
    /// Builds and executes requests for operations under \UserItems
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserItemsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Resume property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.UserItems.Resume.ResumeRequestBuilder Resume
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.UserItems.Resume.ResumeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Jellyfin.OpenApiClient.UserItems.item collection</summary>
        /// <param name="position">The item id.</param>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.UserItems.Item.WithItemItemRequestBuilder"/></returns>
        public global::Soenneker.Jellyfin.OpenApiClient.UserItems.Item.WithItemItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("itemId", position);
                return new global::Soenneker.Jellyfin.OpenApiClient.UserItems.Item.WithItemItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.UserItems.UserItemsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserItemsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/UserItems", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.UserItems.UserItemsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserItemsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/UserItems", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
