// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.LiveTv.LiveStreamFiles.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.LiveTv.LiveStreamFiles
{
    /// <summary>
    /// Builds and executes requests for operations under \LiveTv\LiveStreamFiles
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LiveStreamFilesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Jellyfin.OpenApiClient.LiveTv.LiveStreamFiles.item collection</summary>
        /// <param name="position">Stream id.</param>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.LiveTv.LiveStreamFiles.Item.WithStreamItemRequestBuilder"/></returns>
        public global::Soenneker.Jellyfin.OpenApiClient.LiveTv.LiveStreamFiles.Item.WithStreamItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("streamId", position);
                return new global::Soenneker.Jellyfin.OpenApiClient.LiveTv.LiveStreamFiles.Item.WithStreamItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.LiveTv.LiveStreamFiles.LiveStreamFilesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LiveStreamFilesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/LiveTv/LiveStreamFiles", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.LiveTv.LiveStreamFiles.LiveStreamFilesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LiveStreamFilesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/LiveTv/LiveStreamFiles", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
