// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.System.ActivityLog;
using Soenneker.Jellyfin.OpenApiClient.System.Configuration;
using Soenneker.Jellyfin.OpenApiClient.System.Endpoint;
using Soenneker.Jellyfin.OpenApiClient.System.Info;
using Soenneker.Jellyfin.OpenApiClient.System.Logs;
using Soenneker.Jellyfin.OpenApiClient.System.Ping;
using Soenneker.Jellyfin.OpenApiClient.System.Restart;
using Soenneker.Jellyfin.OpenApiClient.System.Shutdown;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.System
{
    /// <summary>
    /// Builds and executes requests for operations under \System
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SystemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ActivityLog property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.System.ActivityLog.ActivityLogRequestBuilder ActivityLog
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.System.ActivityLog.ActivityLogRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Configuration property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.System.Configuration.ConfigurationRequestBuilder Configuration
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.System.Configuration.ConfigurationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Endpoint property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.System.Endpoint.EndpointRequestBuilder Endpoint
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.System.Endpoint.EndpointRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Info property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.System.Info.InfoRequestBuilder Info
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.System.Info.InfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Logs property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.System.Logs.LogsRequestBuilder Logs
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.System.Logs.LogsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Ping property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.System.Ping.PingRequestBuilder Ping
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.System.Ping.PingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Restart property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.System.Restart.RestartRequestBuilder Restart
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.System.Restart.RestartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Shutdown property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.System.Shutdown.ShutdownRequestBuilder Shutdown
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.System.Shutdown.ShutdownRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.System.SystemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SystemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/System", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.System.SystemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SystemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/System", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
