// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Jellyfin.OpenApiClient.UserItems.Item.Rating;
using Soenneker.Jellyfin.OpenApiClient.UserItems.Item.UserData;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.UserItems.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \UserItems\{itemId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithItemItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Rating property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.UserItems.Item.Rating.RatingRequestBuilder Rating
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.UserItems.Item.Rating.RatingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UserData property</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.UserItems.Item.UserData.UserDataRequestBuilder UserData
        {
            get => new global::Soenneker.Jellyfin.OpenApiClient.UserItems.Item.UserData.UserDataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.UserItems.Item.WithItemItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithItemItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/UserItems/{itemId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Jellyfin.OpenApiClient.UserItems.Item.WithItemItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithItemItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/UserItems/{itemId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
