// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.Models
{
    /// <summary>
    /// A MediaBrowser.Model.Dlna.DeviceProfile represents a set of metadata which determines which content a certain device is able to play.Specifically, it defines the supported &lt;see cref=&quot;P:MediaBrowser.Model.Dlna.DeviceProfile.ContainerProfiles&quot;&gt;containers&lt;/see&gt; and&lt;see cref=&quot;P:MediaBrowser.Model.Dlna.DeviceProfile.CodecProfiles&quot;&gt;codecs&lt;/see&gt; (video and/or audio, including codec profiles and levels)the device is able to direct play (without transcoding or remuxing),as well as which &lt;see cref=&quot;P:MediaBrowser.Model.Dlna.DeviceProfile.TranscodingProfiles&quot;&gt;containers/codecs to transcode to&lt;/see&gt; in case it isn&apos;t.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeviceProfile : IParsable
    {
        /// <summary>Gets or sets the codec profiles.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.CodecProfile>? CodecProfiles { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.CodecProfile> CodecProfiles { get; set; }
#endif
        /// <summary>Gets or sets the container profiles. Failing to meet these optional conditions causes transcoding to occur.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.ContainerProfile>? ContainerProfiles { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.ContainerProfile> ContainerProfiles { get; set; }
#endif
        /// <summary>Gets or sets the direct play profiles.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.DirectPlayProfile>? DirectPlayProfiles { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.DirectPlayProfile> DirectPlayProfiles { get; set; }
#endif
        /// <summary>Gets or sets the unique internal identifier.</summary>
        public Guid? Id { get; set; }
        /// <summary>Gets or sets the maximum allowed bitrate for statically streamed content (= direct played files).</summary>
        public int? MaxStaticBitrate { get; set; }
        /// <summary>Gets or sets the maximum allowed bitrate for statically streamed (= direct played) music files.</summary>
        public int? MaxStaticMusicBitrate { get; set; }
        /// <summary>Gets or sets the maximum allowed bitrate for all streamed content.</summary>
        public int? MaxStreamingBitrate { get; set; }
        /// <summary>Gets or sets the maximum allowed bitrate for transcoded music streams.</summary>
        public int? MusicStreamingTranscodingBitrate { get; set; }
        /// <summary>Gets or sets the name of this device profile. User profiles must have a unique name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Gets or sets the subtitle profiles.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.SubtitleProfile>? SubtitleProfiles { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.SubtitleProfile> SubtitleProfiles { get; set; }
#endif
        /// <summary>Gets or sets the transcoding profiles.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.TranscodingProfile>? TranscodingProfiles { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.TranscodingProfile> TranscodingProfiles { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.Models.DeviceProfile"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Jellyfin.OpenApiClient.Models.DeviceProfile CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Jellyfin.OpenApiClient.Models.DeviceProfile();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "CodecProfiles", n => { CodecProfiles = n.GetCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.CodecProfile>(global::Soenneker.Jellyfin.OpenApiClient.Models.CodecProfile.CreateFromDiscriminatorValue)?.AsList(); } },
                { "ContainerProfiles", n => { ContainerProfiles = n.GetCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.ContainerProfile>(global::Soenneker.Jellyfin.OpenApiClient.Models.ContainerProfile.CreateFromDiscriminatorValue)?.AsList(); } },
                { "DirectPlayProfiles", n => { DirectPlayProfiles = n.GetCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.DirectPlayProfile>(global::Soenneker.Jellyfin.OpenApiClient.Models.DirectPlayProfile.CreateFromDiscriminatorValue)?.AsList(); } },
                { "Id", n => { Id = n.GetGuidValue(); } },
                { "MaxStaticBitrate", n => { MaxStaticBitrate = n.GetIntValue(); } },
                { "MaxStaticMusicBitrate", n => { MaxStaticMusicBitrate = n.GetIntValue(); } },
                { "MaxStreamingBitrate", n => { MaxStreamingBitrate = n.GetIntValue(); } },
                { "MusicStreamingTranscodingBitrate", n => { MusicStreamingTranscodingBitrate = n.GetIntValue(); } },
                { "Name", n => { Name = n.GetStringValue(); } },
                { "SubtitleProfiles", n => { SubtitleProfiles = n.GetCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.SubtitleProfile>(global::Soenneker.Jellyfin.OpenApiClient.Models.SubtitleProfile.CreateFromDiscriminatorValue)?.AsList(); } },
                { "TranscodingProfiles", n => { TranscodingProfiles = n.GetCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.TranscodingProfile>(global::Soenneker.Jellyfin.OpenApiClient.Models.TranscodingProfile.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.CodecProfile>("CodecProfiles", CodecProfiles);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.ContainerProfile>("ContainerProfiles", ContainerProfiles);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.DirectPlayProfile>("DirectPlayProfiles", DirectPlayProfiles);
            writer.WriteGuidValue("Id", Id);
            writer.WriteIntValue("MaxStaticBitrate", MaxStaticBitrate);
            writer.WriteIntValue("MaxStaticMusicBitrate", MaxStaticMusicBitrate);
            writer.WriteIntValue("MaxStreamingBitrate", MaxStreamingBitrate);
            writer.WriteIntValue("MusicStreamingTranscodingBitrate", MusicStreamingTranscodingBitrate);
            writer.WriteStringValue("Name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.SubtitleProfile>("SubtitleProfiles", SubtitleProfiles);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.TranscodingProfile>("TranscodingProfiles", TranscodingProfiles);
        }
    }
}
#pragma warning restore CS0618
