// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.Models
{
    /// <summary>
    /// A DTO representing device information.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeviceInfoDto : IParsable
    {
        /// <summary>Gets or sets the access token.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessToken { get; set; }
#nullable restore
#else
        public string AccessToken { get; set; }
#endif
        /// <summary>Gets or sets the name of the application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppName { get; set; }
#nullable restore
#else
        public string AppName { get; set; }
#endif
        /// <summary>Gets or sets the application version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppVersion { get; set; }
#nullable restore
#else
        public string AppVersion { get; set; }
#endif
        /// <summary>Gets or sets the capabilities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Jellyfin.OpenApiClient.Models.ClientCapabilitiesDto? Capabilities { get; set; }
#nullable restore
#else
        public global::Soenneker.Jellyfin.OpenApiClient.Models.ClientCapabilitiesDto Capabilities { get; set; }
#endif
        /// <summary>Gets or sets the custom name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomName { get; set; }
#nullable restore
#else
        public string CustomName { get; set; }
#endif
        /// <summary>Gets or sets the date last modified.</summary>
        public DateTimeOffset? DateLastActivity { get; set; }
        /// <summary>Gets or sets the icon URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IconUrl { get; set; }
#nullable restore
#else
        public string IconUrl { get; set; }
#endif
        /// <summary>Gets or sets the identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Gets or sets the last user identifier.</summary>
        public Guid? LastUserId { get; set; }
        /// <summary>Gets or sets the last name of the user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastUserName { get; set; }
#nullable restore
#else
        public string LastUserName { get; set; }
#endif
        /// <summary>Gets or sets the name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.Models.DeviceInfoDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Jellyfin.OpenApiClient.Models.DeviceInfoDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Jellyfin.OpenApiClient.Models.DeviceInfoDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AccessToken", n => { AccessToken = n.GetStringValue(); } },
                { "AppName", n => { AppName = n.GetStringValue(); } },
                { "AppVersion", n => { AppVersion = n.GetStringValue(); } },
                { "Capabilities", n => { Capabilities = n.GetObjectValue<global::Soenneker.Jellyfin.OpenApiClient.Models.ClientCapabilitiesDto>(global::Soenneker.Jellyfin.OpenApiClient.Models.ClientCapabilitiesDto.CreateFromDiscriminatorValue); } },
                { "CustomName", n => { CustomName = n.GetStringValue(); } },
                { "DateLastActivity", n => { DateLastActivity = n.GetDateTimeOffsetValue(); } },
                { "IconUrl", n => { IconUrl = n.GetStringValue(); } },
                { "Id", n => { Id = n.GetStringValue(); } },
                { "LastUserId", n => { LastUserId = n.GetGuidValue(); } },
                { "LastUserName", n => { LastUserName = n.GetStringValue(); } },
                { "Name", n => { Name = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AccessToken", AccessToken);
            writer.WriteStringValue("AppName", AppName);
            writer.WriteStringValue("AppVersion", AppVersion);
            writer.WriteObjectValue<global::Soenneker.Jellyfin.OpenApiClient.Models.ClientCapabilitiesDto>("Capabilities", Capabilities);
            writer.WriteStringValue("CustomName", CustomName);
            writer.WriteDateTimeOffsetValue("DateLastActivity", DateLastActivity);
            writer.WriteStringValue("IconUrl", IconUrl);
            writer.WriteStringValue("Id", Id);
            writer.WriteGuidValue("LastUserId", LastUserId);
            writer.WriteStringValue("LastUserName", LastUserName);
            writer.WriteStringValue("Name", Name);
        }
    }
}
#pragma warning restore CS0618
