// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.Models
{
    /// <summary>
    /// Library type options dto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LibraryTypeOptionsDto : IParsable
    {
        /// <summary>Gets or sets the default image options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.ImageOption>? DefaultImageOptions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.ImageOption> DefaultImageOptions { get; set; }
#endif
        /// <summary>Gets or sets the image fetchers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>? ImageFetchers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto> ImageFetchers { get; set; }
#endif
        /// <summary>Gets or sets the metadata fetchers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>? MetadataFetchers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto> MetadataFetchers { get; set; }
#endif
        /// <summary>Gets or sets the similar item providers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>? SimilarItemProviders { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto> SimilarItemProviders { get; set; }
#endif
        /// <summary>Gets or sets the supported image types.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.ImageType?>? SupportedImageTypes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.ImageType?> SupportedImageTypes { get; set; }
#endif
        /// <summary>Gets or sets the type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryTypeOptionsDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryTypeOptionsDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryTypeOptionsDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "DefaultImageOptions", n => { DefaultImageOptions = n.GetCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.ImageOption>(global::Soenneker.Jellyfin.OpenApiClient.Models.ImageOption.CreateFromDiscriminatorValue)?.AsList(); } },
                { "ImageFetchers", n => { ImageFetchers = n.GetCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>(global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "MetadataFetchers", n => { MetadataFetchers = n.GetCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>(global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "SimilarItemProviders", n => { SimilarItemProviders = n.GetCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>(global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "SupportedImageTypes", n => { SupportedImageTypes = n.GetCollectionOfEnumValues<global::Soenneker.Jellyfin.OpenApiClient.Models.ImageType>()?.AsList(); } },
                { "Type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.ImageOption>("DefaultImageOptions", DefaultImageOptions);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>("ImageFetchers", ImageFetchers);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>("MetadataFetchers", MetadataFetchers);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>("SimilarItemProviders", SimilarItemProviders);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Jellyfin.OpenApiClient.Models.ImageType>("SupportedImageTypes", SupportedImageTypes);
            writer.WriteStringValue("Type", Type);
        }
    }
}
#pragma warning restore CS0618
