// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.Models
{
    /// <summary>
    /// Library options result dto.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LibraryOptionsResultDto : IParsable
    {
        /// <summary>Gets or sets the list of lyric fetchers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>? LyricFetchers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto> LyricFetchers { get; set; }
#endif
        /// <summary>Gets or sets the list of MediaSegment Providers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>? MediaSegmentProviders { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto> MediaSegmentProviders { get; set; }
#endif
        /// <summary>Gets or sets the metadata readers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>? MetadataReaders { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto> MetadataReaders { get; set; }
#endif
        /// <summary>Gets or sets the metadata savers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>? MetadataSavers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto> MetadataSavers { get; set; }
#endif
        /// <summary>Gets or sets the subtitle fetchers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>? SubtitleFetchers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto> SubtitleFetchers { get; set; }
#endif
        /// <summary>Gets or sets the type options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryTypeOptionsDto>? TypeOptions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryTypeOptionsDto> TypeOptions { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionsResultDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionsResultDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionsResultDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "LyricFetchers", n => { LyricFetchers = n.GetCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>(global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "MediaSegmentProviders", n => { MediaSegmentProviders = n.GetCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>(global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "MetadataReaders", n => { MetadataReaders = n.GetCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>(global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "MetadataSavers", n => { MetadataSavers = n.GetCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>(global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "SubtitleFetchers", n => { SubtitleFetchers = n.GetCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>(global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "TypeOptions", n => { TypeOptions = n.GetCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryTypeOptionsDto>(global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryTypeOptionsDto.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>("LyricFetchers", LyricFetchers);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>("MediaSegmentProviders", MediaSegmentProviders);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>("MetadataReaders", MetadataReaders);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>("MetadataSavers", MetadataSavers);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryOptionInfoDto>("SubtitleFetchers", SubtitleFetchers);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryTypeOptionsDto>("TypeOptions", TypeOptions);
        }
    }
}
#pragma warning restore CS0618
