// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.Models
{
    /// <summary>
    /// Class PlaybackInfoResponse.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PlaybackInfoResponse : IParsable
    {
        /// <summary>Gets or sets the error code.</summary>
        public global::Soenneker.Jellyfin.OpenApiClient.Models.PlaybackInfoResponse_ErrorCode? ErrorCode { get; set; }
        /// <summary>Gets or sets the media sources.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.MediaSourceInfo>? MediaSources { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.MediaSourceInfo> MediaSources { get; set; }
#endif
        /// <summary>Gets or sets the play session identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlaySessionId { get; set; }
#nullable restore
#else
        public string PlaySessionId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.Models.PlaybackInfoResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Jellyfin.OpenApiClient.Models.PlaybackInfoResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Jellyfin.OpenApiClient.Models.PlaybackInfoResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ErrorCode", n => { ErrorCode = n.GetEnumValue<global::Soenneker.Jellyfin.OpenApiClient.Models.PlaybackInfoResponse_ErrorCode>(); } },
                { "MediaSources", n => { MediaSources = n.GetCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.MediaSourceInfo>(global::Soenneker.Jellyfin.OpenApiClient.Models.MediaSourceInfo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "PlaySessionId", n => { PlaySessionId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Jellyfin.OpenApiClient.Models.PlaybackInfoResponse_ErrorCode>("ErrorCode", ErrorCode);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.MediaSourceInfo>("MediaSources", MediaSources);
            writer.WriteStringValue("PlaySessionId", PlaySessionId);
        }
    }
}
#pragma warning restore CS0618
