// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Jellyfin.OpenApiClient.Models
{
    /// <summary>
    /// Contains informations about the systems storage.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SystemStorageDto : IParsable
    {
        /// <summary>Gets or sets the Storage information of the cache folder.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto? CacheFolder { get; set; }
#nullable restore
#else
        public global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto CacheFolder { get; set; }
#endif
        /// <summary>Gets or sets the Storage information of the folder where images are cached.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto? ImageCacheFolder { get; set; }
#nullable restore
#else
        public global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto ImageCacheFolder { get; set; }
#endif
        /// <summary>Gets or sets the Storage information of the folder where metadata is stored.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto? InternalMetadataFolder { get; set; }
#nullable restore
#else
        public global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto InternalMetadataFolder { get; set; }
#endif
        /// <summary>Gets or sets the storage informations of all libraries.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryStorageDto>? Libraries { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryStorageDto> Libraries { get; set; }
#endif
        /// <summary>Gets or sets the Storage information of the folder where logfiles are saved to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto? LogFolder { get; set; }
#nullable restore
#else
        public global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto LogFolder { get; set; }
#endif
        /// <summary>Gets or sets the Storage information of the program data folder.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto? ProgramDataFolder { get; set; }
#nullable restore
#else
        public global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto ProgramDataFolder { get; set; }
#endif
        /// <summary>Gets or sets the Storage information of the transcoding cache.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto? TranscodingTempFolder { get; set; }
#nullable restore
#else
        public global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto TranscodingTempFolder { get; set; }
#endif
        /// <summary>Gets or sets the Storage information of the web UI resources folder.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto? WebFolder { get; set; }
#nullable restore
#else
        public global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto WebFolder { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Jellyfin.OpenApiClient.Models.SystemStorageDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Jellyfin.OpenApiClient.Models.SystemStorageDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Jellyfin.OpenApiClient.Models.SystemStorageDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "CacheFolder", n => { CacheFolder = n.GetObjectValue<global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto>(global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto.CreateFromDiscriminatorValue); } },
                { "ImageCacheFolder", n => { ImageCacheFolder = n.GetObjectValue<global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto>(global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto.CreateFromDiscriminatorValue); } },
                { "InternalMetadataFolder", n => { InternalMetadataFolder = n.GetObjectValue<global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto>(global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto.CreateFromDiscriminatorValue); } },
                { "Libraries", n => { Libraries = n.GetCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryStorageDto>(global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryStorageDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "LogFolder", n => { LogFolder = n.GetObjectValue<global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto>(global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto.CreateFromDiscriminatorValue); } },
                { "ProgramDataFolder", n => { ProgramDataFolder = n.GetObjectValue<global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto>(global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto.CreateFromDiscriminatorValue); } },
                { "TranscodingTempFolder", n => { TranscodingTempFolder = n.GetObjectValue<global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto>(global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto.CreateFromDiscriminatorValue); } },
                { "WebFolder", n => { WebFolder = n.GetObjectValue<global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto>(global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto>("CacheFolder", CacheFolder);
            writer.WriteObjectValue<global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto>("ImageCacheFolder", ImageCacheFolder);
            writer.WriteObjectValue<global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto>("InternalMetadataFolder", InternalMetadataFolder);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Jellyfin.OpenApiClient.Models.LibraryStorageDto>("Libraries", Libraries);
            writer.WriteObjectValue<global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto>("LogFolder", LogFolder);
            writer.WriteObjectValue<global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto>("ProgramDataFolder", ProgramDataFolder);
            writer.WriteObjectValue<global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto>("TranscodingTempFolder", TranscodingTempFolder);
            writer.WriteObjectValue<global::Soenneker.Jellyfin.OpenApiClient.Models.FolderStorageDto>("WebFolder", WebFolder);
        }
    }
}
#pragma warning restore CS0618
